MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    EXTERNAL_PROPOSAL: False
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 16 # total classes : 15 + 1
    NAME_OLD_CLASSES: [ ]
    NAME_NEW_CLASSES: [ "airplane", "baseballfield", "bridge", "groundtrackfield", "vehicle", "ship", "tenniscourt", "airport", "chimney", "dam", "basketballcourt", "Expressway-Service-area", "Expressway-toll-station", "golffield", "harbor" ]
    NAME_EXCLUDED_CLASSES: [ "overpass", "stadium", "storagetank", "trainstation", "windmill" ]
DATASETS:
  TRAIN: ("dior_train",)
  TEST: ("dior_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.01 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (9632, 13207)
  MAX_ITER: 14398 # number of iteration
  CHECKPOINT_PERIOD: 13207 # number of iteration to generate check point
  IMS_PER_BATCH: 8 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 8 # number of images per batch
OUTPUT_DIR: "log/DIOR/15-5/ABR/STEP0" # path to store the result
TENSORBOARD_DIR: "log/DIOR/15-5/ABR/STEP0" # path to store tensorboard info