MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "log/DIOR/15-5/ABR/STEP0/model_trimmed.pth"
  SOURCE_WEIGHT: "log/DIOR/15-5/ABR/STEP0/model_trimmed.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 21 # total classes : 20 + 1
    NAME_OLD_CLASSES: [ "airplane", "baseballfield", "bridge", "groundtrackfield", "vehicle", "ship", "tenniscourt", "airport", "chimney", "dam", "basketballcourt", "Expressway-Service-area", "Expressway-toll-station", "golffield", "harbor" ]
    NAME_NEW_CLASSES: [ "overpass", "stadium", "storagetank", "trainstation", "windmill" ]
    NAME_EXCLUDED_CLASSES: [ ]
DATASETS:
  TRAIN: ("rb_dior_train",)
  TEST: ("dior_test",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (4314,)  # 12500
  MAX_ITER: 5177 # number of iteration
  CHECKPOINT_PERIOD: 4314 # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "log" # path to store the result
TENSORBOARD_DIR: "log"