MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "log/DOTA/10-5/STEP0/model_trimmed.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 2000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 16 # total classes : 15 + 1
    NAME_OLD_CLASSES: [ "plane", "baseball-diamond", "bridge", "ground-track-field", "small-vehicle", "large-vehicle", "ship", "tennis-court", "basketball-court", "storage-tank" ]
    NAME_NEW_CLASSES: [ "soccer-ball-field", "roundabout", "harbor", "swimming-pool", "helicopter" ]
    NAME_EXCLUDED_CLASSES: [ ]
DATASETS:
  TRAIN: ("dota_train",)
  TEST: ("dota_test",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1333
SOLVER:
  BASE_LR: 0.001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (4498,)
  MAX_ITER: 5397 # number of iteration
  CHECKPOINT_PERIOD: 4498 # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "log" # path to store the result
TENSORBOARD_DIR: "log" # path to store tensorboard info