MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "log/DIOR/19-1/ABR/STEP0/model_trimmed.pth"
  SOURCE_WEIGHT: "log/DIOR/19-1/ABR/STEP0/model_trimmed.pth"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 21 # total classes : 20 + 1
    NAME_OLD_CLASSES: [ "airplane", "baseballfield", "bridge", "groundtrackfield", "vehicle", "ship", "tenniscourt", "airport", "chimney", "dam", "basketballcourt", "Expressway-Service-area", "Expressway-toll-station", "golffield", "harbor", "overpass", "stadium", "storagetank", "trainstation" ]
    NAME_NEW_CLASSES: [ "windmill" ]
    NAME_EXCLUDED_CLASSES: [ ]
DATASETS:
  TRAIN: ("rb_dior_train",)
  TEST: ("dior_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (2000,)
  MAX_ITER: 2500 # number of iteration
  CHECKPOINT_PERIOD: 2000 # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "log" # path to store the result
TENSORBOARD_DIR: "log"