MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 2000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 8
    NAME_OLD_CLASSES: [ ]
    NAME_EXCLUDED_CLASSES: [ "plane", "baseball-diamond", "bridge", "ground-track-field", "small-vehicle", "large-vehicle", "ship", "tennis-court" ]
    NAME_NEW_CLASSES: [ "basketball-court", "storage-tank", "soccer-ball-field", "roundabout", "harbor", "swimming-pool", "helicopter" ]
DATASETS:
  TRAIN: ("dota_train",)
  TEST: ("dota_test",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1333
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  STEPS: (4446, 6076)
  MAX_ITER: 6619
  IMS_PER_BATCH: 8
  MOMENTUM: 0.9
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "log/DOTA/8-7/FT"
TENSORBOARD_DIR: "log/DOTA/8-7/FT"
FINETUNE:
  ENABLE: True
